# Generated by Django 5.0.6 on 2024-06-08 15:18

import car_bazaar_system.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_bazaar_system", "0002_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="DriveType",
            field=models.CharField(default="RWD", max_length=255),
        ),
        migrations.AddField(
            model_name="car",
            name="EngineSize",
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name="car",
            name="FuelType",
            field=models.CharField(default="Gasoline", max_length=255),
        ),
        migrations.AddField(
            model_name="car",
            name="Power",
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name="car",
            name="Transmission",
            field=models.CharField(default="Automatic", max_length=255),
        ),
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(upload_to=car_bazaar_system.models.get_upload_to),
        ),
    ]
