"""empty message

Revision ID: 192b2ac0a912
Revises: 9d15c7757822
Create Date: 2023-12-06 20:14:29.971716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192b2ac0a912'
down_revision: Union[str, None] = '9d15c7757822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('BodyType', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'BodyType')
    # ### end Alembic commands ###
