"""Db migration 3

Revision ID: 1dbb045ff3d5
Revises: 9b011dbaf8af
Create Date: 2023-12-02 23:53:31.725977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dbb045ff3d5'
down_revision: Union[str, None] = '9b011dbaf8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
