"""empty message

Revision ID: 21a5ccd6245e
Revises: f1e61a29d451
Create Date: 2023-12-03 00:24:17.358442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21a5ccd6245e'
down_revision: Union[str, None] = 'f1e61a29d451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('Asaaaaaaaaaaaa', sa.String(length=255), nullable=True))
    op.drop_column('cars', 'Abcdef')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('Abcdef', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('cars', 'Asaaaaaaaaaaaa')
    # ### end Alembic commands ###
