"""Db migration 3

Revision ID: 25d5790c2c91
Revises: 96270b6f4e2d
Create Date: 2023-12-03 00:01:30.119790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d5790c2c91'
down_revision: Union[str, None] = '96270b6f4e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('PictureLink', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'PictureLink')
    # ### end Alembic commands ###
