"""empty message

Revision ID: 9d15c7757822
Revises: 21a5ccd6245e
Create Date: 2023-12-03 00:29:47.088267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9d15c7757822'
down_revision: Union[str, None] = '21a5ccd6245e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'Asaaaaaaaaaaaa')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('Asaaaaaaaaaaaa', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
