"""Db migration does it work  ufhr4eiufhirtghiruthgiurtg irtghuitgigt

Revision ID: f1e61a29d451
Revises: d367337f769e
Create Date: 2023-12-03 00:21:57.818891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e61a29d451'
down_revision: Union[str, None] = 'd367337f769e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('Abcdef', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'Abcdef')
    # ### end Alembic commands ###
