"""empty message

Revision ID: f5aeda64608a
Revises: 192b2ac0a912
Create Date: 2024-01-11 20:04:08.495662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5aeda64608a'
down_revision: Union[str, None] = '192b2ac0a912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('NumberOfReviews', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('ReviewLink', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'ReviewLink')
    op.drop_column('cars', 'NumberOfReviews')
    # ### end Alembic commands ###
